name: Continuous Integration Workflow
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      VERSION: 0.0.${{ github.run_number }}-preview
    steps:
      - uses: actions/checkout@master

      - run: docker build -t wled/test:latest --build-arg VERSION . --target test
      - run: docker run wled/test:latest

      - run: docker build -t wled/push:latest --build-arg VERSION . --target push
      - run: docker run wled/push:latest --api-key ${{ secrets.NUGET_API_KEY }}
        if: github.ref == 'refs/heads/master'
